[package]
name = "rust_snake"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.3.13"
rand = "0.8.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true