pub(crate) mod snake_body;
pub(crate) mod snake_body_16;
pub(crate) mod snake_body_32;
pub(crate) mod snake_bonus;
pub(crate) mod snake_head;
pub(crate) mod snake_bg1;
pub(crate) mod snake_bg2;
pub(crate) mod snake_bg3;
pub(crate) mod snake_bg4;