use core_std::vec::Vec;
#[derive(Debug, Clone, Copy)]
pub struct Pos
{    
    pub x:i16,
    pub y:i16,
}

fn main() 
{
    let mut bonus_list: Vec<u8> = Vec::new();
    println!("{:?}", bonus_list);
    bonus_list.push(16);
    bonus_list.push(32);
    bonus_list.push(34);
    bonus_list.push(56);
    println!("{:?}", bonus_list);

    //POS
    let mut pos_list: Vec<Pos> = Vec::new();
    println!("{:?}", pos_list);
    pos_list.push(Pos { x: 0, y: 0 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    pos_list.push(Pos { x: 22, y: 22 });
    println!("{:?}", pos_list);
}