[package]
name = "core_std_main"
version = "0.1.0"
edition = "2021"

[dependencies]
core_std = { path = "../core_std"}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = 'abort'